# -*- coding: utf-8 -*-
print("Вопрос №1")
x = raw_input("Характеризуйте себя несколькими словами:\n").strip()
z = x.split(" ")
print(max(z, key=len))
print("Вопрос №2")
q = raw_input("Перечислите через точку с запятой Ваши профессионльные навыки:\n").strip()
w = q.split(";")
print(max(w, key=len))
print('Вопрос №3')
q = raw_input("Перечислите ваши положительные черты характера:\n").strip()
a = (raw_input("Введите Ваш любимый смвол:\n"))
q = q.replace(' ',a)
w = q.split(a)
print(min(w, key=len))
print("Вопрос №4")
t = raw_input('Введите Ваши вредные привычки:\n')
f = raw_input("Какая привычка из перечисленных самая вредная по-вашему мнению:\n")
ri=f.split(' ')
for i in ri:
    if i == f:
        print (i)
print("Вопрос №5")
rez = raw_input('Перечислите где Вы раньше работали, разделяйте названия учереждений точкой с запятой:\n')
print(len(rez.split(';')))
